[package]
name = "mate"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "mate"
path = "src/mate.rs"

[[bin]]
name = "mate-collector"
path = "src/collector.rs"

[dependencies]
clap = "~2.34"
env_logger = "~0.9.0"
log = "~0.4.14"
serde_json = "1.0.72"
tda-sdk = "0.1.2"
