[package]
name = "mate"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tda-sdk = "0.1.1"
serde_json = "1.0.72"
