[package]
name = "mate"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "mate"
path = "src/engine/mate.rs"

[[bin]]
name = "mate-collector"
path = "src/collector/collector.rs"

[[bin]]
name = "mate-api"
path = "src/api/api.rs"

[dependencies]
clap = "~2.34"
env_logger = "~0.9.0"
log = "~0.4.14"
serde_json = "1.0.72"
tda-sdk = "0.1.2"
futures = { version = "0.3.6", default-features = false, features = ["async-await"] }
hyper = "0.13"
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }
serde = {version = "1.0", features = ["derive"] }
route-recognizer = "0.2"
bytes = "0.5"
async-trait = "0.1"
