[package]
name = "mate"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.34"
serde_json = "1.0.72"
tda-sdk = "0.1.2"
