[package]
name = "mate"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
rust_decimal = "1.17"
rust_decimal_macros = "1.17"
tda-sdk = "0.1.1"
