apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mate
  name: mate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mate
  template:
    metadata:
      labels:
        app: mate
    spec:
      containers:
      - name: mate
        image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
        {{- if eq .Values.env "staging" }}
        imagePullPolicy: Always
        {{- else }}
        imagePullPolicy: IfNotPresent
        {{- end }}
        env:
        - name: ENV
          value: {{ .Values.env }}
        {{- if or .Values.accounts.tdameritrade.enabled .Values.accounts.kraken.enabled }}
        envFrom:
        {{- if .Values.accounts.tdameritrade.enabled }}
        - secretRef:
            name: {{ .Values.accounts.tdameritrade.existingSecret }}
        {{- end }}
        {{- if .Values.accounts.kraken.enabled }}
        - secretRef:
            name: {{ .Values.accounts.kraken.existingSecret }}
        {{- end }}
        {{- if .Values.s3.enabled }}
        - configMapRef:
            name: {{ .Values.s3.bucketName }}
        - secretRef:
            name: {{ .Values.s3.bucketName }}
        {{- end }}
        {{- end }}
      imagePullSecrets:
      - name: regcred
{{ if .Values.api.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mate-api
  name: mate-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mate-api
  template:
    metadata:
      labels:
        app: mate-api
    spec:
      containers:
      - name: mate-api
        image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
        command:
        - mate-api
        args:
        - -vv
        - --postgres-hostname
        - mate-postgresql
        env:
        - name: ENV
          value: {{ .Values.env }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mate-postgresql
              key: postgresql-password
        - name: MATE_SALT
          {{- if .Values.salt.existingSecret }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.salt.existingSecret }}
              key: salt
          {{- else }}
          valueFrom:
            secretKeyRef:
              name: mate-salt
              key: salt
          {{- end }}
        {{- if eq .Values.env "staging" }}
        imagePullPolicy: Always
        {{- else }}
        imagePullPolicy: IfNotPresent
        {{- end }}
        ports:
        - name: web
          containerPort: 8000
      imagePullSecrets:
      - name: regcred
{{- end }}