{{- if .Values.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.api.ingress.clusterIssuer }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.api.ingress.hostname }}
    nginx.ingress.kubernetes.io/enable-cors: "true"
  labels:
    app: mate-api
  name: mate-api
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.api.ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: mate-api
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Values.api.ingress.hostname }}
    secretName: {{ .Values.api.ingress.tlsSecret }}
{{- end }}