{{- if .Values.s3.enabled }}
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: mate-ceph-bucket
spec:
  generateBucketName: mate
  storageClassName: rook-ceph-bucket
{{- end }}