{{- if .Values.s3.enabled }}
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {{ .Values.s3.bucketName }}
spec:
  bucketName: {{ .Values.s3.bucketName }}
  storageClassName: rook-ceph-bucket
{{- end }}
