{{- if .Values.salt.value }}
apiVersion: v1
kind: Secret
metadata:
  name: mate-salt
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  value: {{ .Values.salt.value | b64enc }}
{{- end }}