apiVersion: v1
kind: Service
metadata:
  name: mate-collector
  labels:
    app: mate-collector
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: mate-collector
{{- if .Values.api.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: mate-api
  labels:
    app: mate-api
spec:
  ports:
  - port: 80
    name: web
    targetPort: 8000
  clusterIP: None
  selector:
    app: mate-api
{{- end }}
